server:
  port: 8080

spring:
  datasource:
    url: jdbc:dm://10.0.0.10:5236/MES
    username: ${DB_USER:SYSDBA}
    password: ${DB_PWD:SYSDBA}
    dynamic:
      datasource:
        master:
          url: jdbc:dm://10.0.0.10:5236/MES
        slave:
          url: jdbc:dm://10.0.0.11:5236/MES_SLAVE
  jpa:
    show-sql: false
  redis:
    host: 10.0.0.20
    port: 6379
    password: ${REDIS_PWD:}
